[package]
name = "practice"
version = "0.1"
lean_version = "nightly-2018-10-28"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "78f1949719676db358ea5e68e211a73e2ce95e7b"}
